/**
 * Exact-match EN→DE dictionary for Vector's interactive labs (canvas labels,
 * meter titles, control labels, in-lab buttons) — the same mechanism the other
 * courses use.
 *
 * The canvas is not React, so it cannot read the language context; instead the
 * LanguageProvider calls setLabDictionary() on every switch and the drawing
 * primitives translate through tl(). Keys must match the source strings
 * character-exactly. Dynamic strings (template literals with numbers) fall
 * through untranslated by design — they are mostly numbers and units.
 */

export const LAB_DE: Record<string, string> = {
  /* ---- shared control vocabulary ---- */
  Time: "Zeit",
  Position: "Position",
  Mass: "Masse",
  Friction: "Reibung",
  World: "Welt",
  Frequency: "Frequenz",
  frequency: "Frequenz",
  none: "keine",
  Earth: "Erde",
  Moon: "Mond",

  /* ---- unit 0: motion ---- */
  "Velocity, seconds 0–4": "Geschwindigkeit, Sekunden 0–4",
  "Velocity, seconds 4–8": "Geschwindigkeit, Sekunden 4–8",
  "Velocity, seconds 8–12": "Geschwindigkeit, Sekunden 8–12",
  "right now": "gerade jetzt",
  "slope: uphill": "Steigung: bergauf",
  "slope: downhill": "Steigung: bergab",
  "slope: flat": "Steigung: flach",
  "the graph's slope": "die Steigung des Graphen",
  "IS the velocity": "IST die Geschwindigkeit",
  "end position": "Endposition",
  "Final position": "Endposition",
  "Flat segments": "Flache Abschnitte",
  Rule: "Regel",
  "slope of x(t) = velocity": "Steigung von x(t) = Geschwindigkeit",
  "Moon (1.6)": "Mond (1,6)",
  "Earth (9.8)": "Erde (9,8)",
  "Jupiter (24.8)": "Jupiter (24,8)",
  "Air resistance": "Luftwiderstand",
  vacuum: "Vakuum",
  air: "Luft",
  speed: "Tempo",
  "terminal velocity": "Endgeschwindigkeit",
  "the square law": "das Quadratgesetz",
  gravity: "Schwerkraft",
  fallen: "gefallen",
  "speed now": "Tempo jetzt",
  Speed: "Tempo",
  "Distance fallen": "Fallstrecke",
  "Terminal velocity": "Endgeschwindigkeit",
  "none (vacuum)": "keine (Vakuum)",
  "steady march": "gleichmäßiger Marsch",
  "free fall": "freier Fall",
  range: "Weite",
  "hang time": "Flugzeit",
  "peak height": "Scheitelhöhe",
  "Launch speed": "Abschussgeschwindigkeit",
  "Launch angle": "Abschusswinkel",
  Range: "Weite",
  "Hang time": "Flugzeit",
  "Peak height": "Scheitelhöhe",
  "Try it": "Probier es",
  "45° — the flat-ground optimum": "45° — das Optimum auf ebenem Boden",

  /* ---- unit 1: forces ---- */
  "net force": "Nettokraft",
  acceleration: "Beschleunigung",
  "friction exceeds the push — a real cart would sit still":
    "die Reibung übersteigt den Schub — ein echter Wagen bliebe stehen",
  "net zero: whatever velocity it has, it keeps":
    "netto null: welche Geschwindigkeit er hat, die behält er",
  "Push force": "Schubkraft",
  "Net force": "Nettokraft",
  Acceleration: "Beschleunigung",
  "Speed after 3 s (from rest)": "Tempo nach 3 s (aus dem Stand)",
  "0 — it never budged": "0 — er hat sich nie gerührt",
  "per kilogram": "pro Kilogramm",
  "slope pull": "Hangabtrieb",
  "friction ceiling": "Reibungsdecke",
  "friction lost — it slides": "Reibung verloren — es rutscht",
  "static friction holds, matching the pull exactly":
    "Haftreibung hält und spiegelt den Zug exakt",
  "slip angle": "Rutschwinkel",
  "µ = tan(slip angle)": "µ = tan(Rutschwinkel)",
  "Board angle": "Brettwinkel",
  Surfaces: "Oberflächen",
  "rubber on wood": "Gummi auf Holz",
  "wood on wood": "Holz auf Holz",
  "steel on ice": "Stahl auf Eis",
  Status: "Status",
  sliding: "rutscht",
  holding: "hält",
  "Slip angle": "Rutschwinkel",
  "µ from the protractor": "µ vom Winkelmesser",
  crashes: "stürzt ab",
  escapes: "entkommt",
  "circular orbit": "Kreisbahn",
  "elliptical orbit": "elliptische Bahn",
  "the speeds": "die Geschwindigkeiten",
  "circular: 7.9": "Kreisbahn: 7,9",
  "(km/s)": "(km/s)",
  "launch speed": "Abschussgeschwindigkeit",
  Fate: "Schicksal",
  "Circular speed": "Kreisbahngeschwindigkeit",
  "Escape speed": "Fluchtgeschwindigkeit",
  "An orbit is": "Eine Umlaufbahn ist",
  "falling, aimed to keep missing": "Fallen, gezielt am Boden vorbei",

  /* ---- unit 2: energy & momentum ---- */
  "the books": "die Bücher",
  "potential (height)": "potenziell (Höhe)",
  "kinetic (speed)": "kinetisch (Tempo)",
  "heat (friction)": "Wärme (Reibung)",
  "total: never changes": "Summe: ändert sich nie",
  "total energy": "Gesamtenergie",
  "ideal bottom speed": "ideales Tempo unten",
  "Drop height": "Fallhöhe",
  "Total energy": "Gesamtenergie",
  "Bottom speed (no friction)": "Tempo unten (ohne Reibung)",
  "With friction": "Mit Reibung",
  "same books, heat account filling": "gleiche Bücher, das Wärmekonto füllt sich",
  before: "vorher",
  after: "nachher",
  "momentum (kg·m/s)": "Impuls (kg·m/s)",
  "kinetic energy (J)": "kinetische Energie (J)",
  "all survived": "alles überlebt",
  "after: cart 1": "nachher: Wagen 1",
  "after: cart 2": "nachher: Wagen 2",
  "Mass of cart 1": "Masse von Wagen 1",
  "Mass of cart 2": "Masse von Wagen 2",
  "Speed of cart 1": "Tempo von Wagen 1",
  Bounciness: "Elastizität",
  elastic: "elastisch",
  sticky: "klebrig",
  Momentum: "Impuls",
  "conserved, always": "erhalten, immer",
  "Kinetic energy kept": "Behaltene kinetische Energie",
  "Watch for": "Achte auf",
  "equal masses swap velocities!": "gleiche Massen tauschen die Geschwindigkeiten!",
  "they stick and share": "sie kleben zusammen und teilen",

  /* ---- unit 3: pendulum ---- */
  "wide swing — the small-angle formula starts to lie":
    "weiter Ausschlag — die Kleinwinkel-Formel beginnt zu lügen",
  "the formula": "die Formel",
  "true period": "wahre Periode",
  "20 swings": "20 Schwingungen",
  "g on this world": "g auf dieser Welt",
  "time 20 swings, then press stop": "stopp 20 Schwingungen, dann drücke Stopp",
  stopwatch: "Stoppuhr",
  "your g = 4π²L/T²": "dein g = 4π²L/T²",
  "String length": "Schnurlänge",
  Amplitude: "Amplitude",
  Stopwatch: "Stoppuhr",
  "■ Stop": "■ Stopp",
  "▶ Start timing": "▶ Zeitmessung starten",
  "True period": "Wahre Periode",
  "20 swings take": "20 Schwingungen dauern",
  "Your measured g": "Dein gemessenes g",
  "time 20 swings, then stop": "miss 20 Schwingungen, dann stopp",
  "not in the formula — on purpose": "nicht in der Formel — mit Absicht",

  /* ---- unit 4: waves & sound ---- */
  "this bead only bobs": "diese Perle wippt nur",
  "medium speed": "Tempo des Mediums",
  "wavelength v/f": "Wellenlänge v/f",
  Medium: "Medium",
  "slack rope (4 m/s)": "lockeres Seil (4 m/s)",
  "taut rope (12 m/s)": "straffes Seil (12 m/s)",
  "steel spring (24 m/s)": "Stahlfeder (24 m/s)",
  "v = f · λ": "v = f · λ",
  "Speed belongs to": "Das Tempo gehört",
  "the medium, not the source": "dem Medium, nicht der Quelle",
  "What travels": "Was reist",
  "the pattern — the rope stays home": "das Muster — das Seil bleibt daheim",
  listener: "Zuhörer",
  "crests crowded ahead — higher pitch": "vorn gedrängte Kämme — höherer Ton",
  "stretched behind — lower pitch": "hinten gedehnt — tieferer Ton",
  "approaching the speed of sound — the crests pile into a wall":
    "nahe der Schallgeschwindigkeit — die Kämme stauen sich zur Wand",
  "heard approaching": "gehört im Anflug",
  "heard receding": "gehört im Wegflug",
  "siren itself": "Sirene selbst",
  "Vehicle speed": "Fahrzeugtempo",
  Approaching: "Im Anflug",
  Receding: "Im Wegflug",
  "Pitch drop at the pass": "Tonabfall beim Vorbeifahren",
  "Works for": "Gilt für",
  "sound, radar, starlight — any wave": "Schall, Radar, Sternenlicht — jede Welle",
  "off resonance — the reflections cancel themselves into a murmur":
    "neben der Resonanz — die Reflexionen löschen sich zu einem Murmeln",
  "driving frequency": "Anregungsfrequenz",
  fundamental: "Grundton",
  "resonances at": "Resonanzen bei",
  "Driving frequency": "Anregungsfrequenz",
  "not in the family": "nicht in der Familie",
  "This string's family": "Die Familie dieser Saite",
  "Shorten the string": "Verkürze die Saite",
  "the whole family shifts up — that's fretting": "die ganze Familie rückt hinauf — das ist Greifen",

  /* ---- unit 5: light ---- */
  "glass (n = 1.5)": "Glas (n = 1,5)",
  "air (n = 1.0)": "Luft (n = 1,0)",
  normal: "Normale",
  "no exit — total internal reflection": "kein Ausgang — Totalreflexion",
  "Snell's law": "Snellius-Gesetz",
  "sin θ₂ would exceed 1": "sin θ₂ läge über 1",
  bending: "Brechung",
  "toward the normal": "zur Normalen hin",
  trapped: "gefangen",
  "away from the normal": "von der Normalen weg",
  "critical angle": "Grenzwinkel",
  "Incoming angle": "Einfallswinkel",
  Direction: "Richtung",
  "air → glass": "Luft → Glas",
  "glass → air": "Glas → Luft",
  "Exit angle": "Austrittswinkel",
  "none — reflected": "keiner — reflektiert",
  "Critical angle (glass→air)": "Grenzwinkel (Glas→Luft)",
  "Past it": "Jenseits davon",
  "the boundary becomes a perfect mirror — fibre optics":
    "wird die Grenze ein perfekter Spiegel — Glasfaser",
  object: "Gegenstand",
  "real image (inverted)": "reelles Bild (umgekehrt)",
  "image beyond the bench →": "Bild jenseits der Bank →",
  "virtual image — a magnifying glass": "virtuelles Bild — eine Lupe",
  "object distance": "Gegenstandsweite",
  "focal length": "Brennweite",
  "image distance": "Bildweite",
  virtual: "virtuell",
  "Object distance": "Gegenstandsweite",
  "Focal length": "Brennweite",
  "1/f = 1/d₀ + 1/dᵢ": "1/f = 1/d₀ + 1/dᵢ",
  "no real image": "kein reelles Bild",
  Image: "Bild",
  "virtual, upright, enlarged": "virtuell, aufrecht, vergrößert",
  "real, inverted": "reell, umgekehrt",
  Magnification: "Vergrößerung",
  "violet bends hardest": "Violett bricht am stärksten",
  "dispersion: n depends slightly on λ": "Dispersion: n hängt leicht von λ ab",
  radio: "Radio",
  microwave: "Mikrowelle",
  IR: "IR",
  UV: "UV",
  "X-ray": "Röntgen",
  gamma: "Gamma",
  wavelength: "Wellenlänge",
  band: "Band",
  "sky-scattering vs green": "Himmelsstreuung vs. Grün",
  "Wavelength (log scale)": "Wellenlänge (log-Skala)",
  Band: "Band",
  "Visible?": "Sichtbar?",
  "yes — one octave of the keyboard": "ja — eine Oktave der Klaviatur",
  "invisible to eyes, real all the same": "für Augen unsichtbar, trotzdem real",
  "Same wave, same c": "Gleiche Welle, gleiches c",
  "radio to gamma": "von Radio bis Gamma",

  /* ---- unit 6: heat & modern ---- */
  heat: "Wärme",
  "hot → cold, always": "heiß → kalt, immer",
  "thermal equilibrium": "thermisches Gleichgewicht",
  "the compromise": "der Kompromiss",
  "weighted by m·c": "gewichtet mit m·c",
  equilibrium: "Gleichgewicht",
  "heat handed over": "übergebene Wärme",
  "Block 1 temperature": "Temperatur Block 1",
  "Block 2 temperature": "Temperatur Block 2",
  "Block 1 mass": "Masse Block 1",
  "Block 2 mass": "Masse Block 2",
  "Block 1 material": "Material Block 1",
  "Block 2 material": "Material Block 2",
  "water (c = 4186)": "Wasser (c = 4186)",
  "iron (c = 449)": "Eisen (c = 449)",
  "copper (c = 385)": "Kupfer (c = 385)",
  "Meeting point": "Treffpunkt",
  "Thermal bulk 1 (m·c)": "Wärmemasse 1 (m·c)",
  "Thermal bulk 2 (m·c)": "Wärmemasse 2 (m·c)",
  "Water wins because": "Wasser gewinnt, weil",
  "c = 4,186 — a thermal flywheel": "c = 4.186 — ein thermisches Schwungrad",
  metal: "Metall",
  "electrons out — instantly": "Elektronen heraus — sofort",
  "nothing — at any brightness, for any duration":
    "nichts — bei jeder Helligkeit, beliebig lange",
  "one photon's offer": "das Angebot eines Photons",
  "paid — surplus becomes speed": "bezahlt — der Überschuss wird Tempo",
  "insufficient — no sale": "reicht nicht — kein Geschäft",
  "packets don't pool": "Pakete sammeln sich nicht an",
  threshold: "Schwelle",
  "electrons/s": "Elektronen/s",
  "Light frequency": "Lichtfrequenz",
  Brightness: "Helligkeit",
  Electrons: "Elektronen",
  "ejected instantly": "sofort herausgeschlagen",
  "Brightness controls": "Helligkeit bestimmt",
  "how many — never how fast": "wie viele — nie wie schnell",
  "Frequency controls": "Frequenz bestimmt",
  "each electron's energy": "die Energie jedes Elektrons",
  Because: "Weil",
  "E = hf, exact change only": "E = hf, nur passend zahlbar",
  "dashed: the ideal halving · solid: this run's actual luck":
    "gestrichelt: das ideale Halbieren · durchgezogen: das Glück dieses Laufs",
  "the census": "die Zählung",
  "small sample: ragged": "kleine Probe: zackig",
  "big sample: metronomic": "große Probe: metronomisch",
  population: "Population",
  "half-life": "Halbwertszeit",
  "implied age (1/8 left)": "implizites Alter (1/8 übrig)",
  "Starting nuclei": "Anfangskerne",
  "Half-life": "Halbwertszeit",
  "Random seed": "Zufalls-Seed",
  Sample: "Probe",
  "fresh (100%)": "frisch (100 %)",
  "ancient (12.5% left)": "uralt (12,5 % übrig)",
  "Nuclei now (end of run)": "Kerne jetzt (Ende des Laufs)",
  "Any single nucleus": "Jeder einzelne Kern",
  "genuinely unpredictable": "wahrhaft unvorhersagbar",
  "Dating: 1/8 left means": "Datierung: 1/8 übrig heißt",
  "The crowd": "Die Menge",
  "halves on schedule": "halbiert sich nach Fahrplan",
};

let active: Record<string, string> | null = null;

export function setLabDictionary(dict: Record<string, string> | null) {
  active = dict;
}

/** Translate a lab string via the active dictionary; unknown strings pass through. */
export function tl(s: string): string {
  return active?.[s] ?? s;
}
