/**
 * Exact-match EN→DE dictionary for Helix's interactive labs (canvas labels,
 * meter titles, control labels, in-lab buttons) — the same mechanism the other
 * courses use.
 *
 * The canvas is not React, so it cannot read the language context; instead the
 * LanguageProvider calls setLabDictionary() on every switch and the drawing
 * primitives translate through tl(). Keys must match the source strings
 * character-exactly. Dynamic strings (template literals with numbers) fall
 * through untranslated by design — they are mostly numbers and base letters.
 *
 * Prose drawn on the canvas is translated *before* being word-wrapped; a
 * per-line tl() could never match a key once a sentence has been chopped up.
 */

export const LAB_DE: Record<string, string> = {
  /* ---- shared control vocabulary ---- */
  Temperature: "Temperatur",
  Speed: "Geschwindigkeit",
  Reset: "Zurücksetzen",
  Start: "Start",
  Pause: "Pause",
  Step: "Schritt",
  Generation: "Generation",
  Rate: "Rate",
  Time: "Zeit",
  Population: "Population",

  /* ---- unit 0: the cell ---- */
  Organelle: "Organell",
  "Cell type": "Zelltyp",
  "Animal cell": "Tierzelle",
  "Plant cell": "Pflanzenzelle",
  "Bacterial cell": "Bakterienzelle",
  "click a part to identify it": "klicke ein Teil an, um es zu bestimmen",
  Nucleus: "Zellkern",
  Mitochondrion: "Mitochondrium",
  Ribosome: "Ribosom",
  Chloroplast: "Chloroplast",
  "Cell membrane": "Zellmembran",
  "Cell wall": "Zellwand",
  Vacuole: "Vakuole",
  Cytoplasm: "Zytoplasma",

  /* ---- unit 0.3: osmosis ---- */
  "Outside concentration": "Konzentration außen",
  hypotonic: "hypotonisch",
  isotonic: "isotonisch",
  hypertonic: "hypertonisch",
  "water in": "Wasser hinein",
  "water out": "Wasser hinaus",
  balanced: "im Gleichgewicht",
  "cell volume": "Zellvolumen",
  "net water flow": "Netto-Wasserfluss",
  "swells and may burst": "schwillt an und kann platzen",
  "shrinks and shrivels": "schrumpft und schrumpelt",
  "stays put": "bleibt konstant",

  /* ---- unit 1: energy ---- */
  Substrate: "Substrat",
  "Substrate concentration": "Substratkonzentration",
  pH: "pH",
  "reaction rate": "Reaktionsgeschwindigkeit",
  denatured: "denaturiert",
  "active site": "aktives Zentrum",
  "Light intensity": "Lichtintensität",
  "CO₂ level": "CO₂-Gehalt",
  "limiting factor": "begrenzender Faktor",
  light: "Licht",
  temperature: "Temperatur",
  "Oxygen available": "Sauerstoff verfügbar",
  aerobic: "aerob",
  anaerobic: "anaerob",
  "ATP per glucose": "ATP pro Glucose",

  /* ---- unit 2: DNA ---- */
  "Template strand": "Matrizenstrang",
  "mRNA codon": "mRNA-Codon",
  "amino acid": "Aminosäure",
  Protein: "Protein",
  "Mutation type": "Mutationstyp",
  none: "keine",
  substitution: "Substitution",
  insertion: "Insertion",
  deletion: "Deletion",
  silent: "stumm",
  missense: "Missense",
  nonsense: "Nonsense",
  frameshift: "Leserasterverschiebung",
  "reading frame": "Leseraster",

  /* ---- unit 3: genetics ---- */
  "Parent 1": "Elternteil 1",
  "Parent 2": "Elternteil 2",
  dominant: "dominant",
  recessive: "rezessiv",
  Genotype: "Genotyp",
  Phenotype: "Phänotyp",
  "offspring ratio": "Nachkommen-Verhältnis",

  /* ---- unit 4: evolution ---- */
  "Selection pressure": "Selektionsdruck",
  "Mutation rate": "Mutationsrate",
  "allele frequency": "Allelfrequenz",
  generations: "Generationen",
  "Predator vision": "Sicht der Räuber",

  /* ---- unit 5: ecology ---- */
  "Carrying capacity": "Kapazitätsgrenze",
  "Growth rate": "Wachstumsrate",
  producers: "Produzenten",
  "primary consumers": "Primärkonsumenten",
  "secondary consumers": "Sekundärkonsumenten",
  "energy passed on": "weitergegebene Energie",

  /* ---- unit 7: immunity ---- */
  "Bacterial doubling time": "Bakterielle Verdopplungszeit",
  "Phagocytes on patrol": "Phagozyten auf Patrouille",
  "Body temperature": "Körpertemperatur",
  "39 °C fever": "39 °C Fieber",
  "bacteria (log scale)": "Bakterien (log-Skala)",
  "infection cleared": "Infektion geräumt",
  "defenses overwhelmed": "Abwehr überrannt",
  "still fighting": "Kampf läuft noch",
  "the race": "das Rennen",
  "🦠 doubling": "🦠 Verdopplung",
  "🍽 phagocytes": "🍽 Phagozyten",
  "fever active": "Fieber aktiv",
  "germs slowed": "Keime gebremst",
  "defenders sped up": "Verteidiger beschleunigt",
  "Bacteria now": "Bakterien jetzt",
  outcome: "Ausgang",
  cleared: "geräumt",
  overwhelmed: "überrannt",
  contested: "umkämpft",
  "Bacteria after 48 h": "Bakterien nach 48 h",
  "Cleared after": "Geräumt nach",
  Fever: "Fieber",
  "slows germs, speeds defenders": "bremst Keime, beschleunigt Verteidiger",
  off: "aus",
  "Day 0 is": "Tag 0 ist",
  "a real infection": "eine echte Infektion",
  "a vaccine": "eine Impfung",
  "Second exposure on day": "Zweitkontakt an Tag",
  "feeling sick above this line": "über dieser Linie fühlst du dich krank",
  vaccine: "Impfung",
  "first exposure": "Erstkontakt",
  "second exposure": "Zweitkontakt",
  pathogen: "Erreger",
  antibodies: "Antikörper",
  "sick days, 1st round": "Kranktage, 1. Runde",
  "sick days, 2nd round": "Kranktage, 2. Runde",
  "Sick days, first round": "Kranktage, erste Runde",
  "Sick days, second round": "Kranktage, zweite Runde",
  Why: "Warum",
  "memory cells answered in a day": "Gedächtniszellen antworteten in einem Tag",
  "memory still forming": "Gedächtnis bildet sich noch",

  /* ---- unit 8: nerves ---- */
  "Stimulus strength": "Reizstärke",
  "Stimulus rate": "Reizrate",
  "resting −70 mV": "Ruhe −70 mV",
  "threshold −55 mV": "Schwelle −55 mV",
  "peak +40 mV": "Spitze +40 mV",
  "membrane potential": "Membranpotenzial",
  "below threshold — the bump fades, nothing travels": "unter der Schwelle — die Beule verblasst, nichts läuft los",
  "the rule": "die Regel",
  all: "alles",
  or: "oder",
  nothing: "nichts",
  "spike height": "Spitzenhöhe",
  "never varies": "variiert nie",
  "rate does": "die Rate schon",
  "spikes per second": "Spitzen pro Sekunde",
  "Reaches threshold": "Erreicht die Schwelle",
  "Spikes per second": "Spitzen pro Sekunde",
  "Spike height": "Spitzenhöhe",
  "+40 mV, always": "+40 mV, immer",
  "Rate ceiling (refractory)": "Ratendecke (Refraktärzeit)",
  "Excitatory inputs": "Erregende Eingänge",
  "Inhibitory inputs": "Hemmende Eingänge",
  "Drug at the synapse": "Droge an der Synapse",
  stimulant: "Stimulans",
  sedative: "Sedativum",
  "spike travelling": "Impuls unterwegs",
  "the tally": "die Auszählung",
  excitatory: "erregend",
  inhibitory: "hemmend",
  resting: "Ruhe",
  sum: "Summe",
  "threshold −55": "Schwelle −55",
  FIRES: "FEUERT",
  "does not fire": "feuert nicht",
  Membrane: "Membran",
  decision: "Entscheidung",
  spike: "Impuls",
  silence: "Stille",
  "Membrane potential": "Membranpotenzial",
  Decision: "Entscheidung",
  fires: "feuert",
  "stays silent": "bleibt stumm",
  "Drug effect": "Drogenwirkung",
  "inhibition halved": "Hemmung halbiert",
  "inhibition doubled": "Hemmung verdoppelt",

  /* ---- unit 9: biotech ---- */
  Cycles: "Zyklen",
  "Starting molecules": "Startmoleküle",
  Efficiency: "Effizienz",
  denature: "denaturieren",
  anneal: "anlagern",
  extend: "verlängern",
  "one cycle ≈ 90 seconds": "ein Zyklus ≈ 90 Sekunden",
  "copies by cycle (log scale)": "Kopien je Zyklus (log-Skala)",
  "the numbers": "die Zahlen",
  "starting molecules": "Startmoleküle",
  cycles: "Zyklen",
  "per-cycle growth": "Wachstum pro Zyklus",
  "copies now": "Kopien jetzt",
  "gel lane": "Gelspur",
  "band visible": "Bande sichtbar",
  "nothing to see": "nichts zu sehen",
  "detectable ✓": "nachweisbar ✓",
  "below detection": "unter der Nachweisgrenze",
  "needs ~10⁶ copies": "braucht ~10⁶ Kopien",
  copies: "Kopien",
  Copies: "Kopien",
  Detectable: "Nachweisbar",
  "not yet": "noch nicht",
  "Doublings missed": "Verpasste Verdopplungen",
  "efficiency compounds": "Effizienz zinst sich auf",
  "Guide position": "Guide-Position",
  "genomic DNA (one strand, 5′→3′)": "genomische DNA (ein Strang, 5′→3′)",
  "guide RNA": "Guide-RNA",
  "Cas9 cuts both strands here": "Cas9 schneidet hier beide Stränge",
  "base-pair matches": "Basenpaar-Treffer",
  "PAM (NGG) next door": "PAM (NGG) nebenan",
  result: "Ergebnis",
  "clean cut": "sauberer Schnitt",
  "off-target risk!": "Off-Target-Risiko!",
  "no cut": "kein Schnitt",
  match: "Treffer",
  Matches: "Treffer",
  "PAM present": "PAM vorhanden",
  "cuts here": "schneidet hier",
  "might cut — off-target!": "könnte schneiden — Off-Target!",
  "does not cut": "schneidet nicht",
  yes: "ja",
  no: "nein",
};

let active: Record<string, string> | null = null;

export function setLabDictionary(dict: Record<string, string> | null) {
  active = dict;
}

/** Translate a lab string via the active dictionary; unknown strings pass through. */
export function tl(s: string): string {
  return active?.[s] ?? s;
}
