/**
 * All 118 elements — the data behind the periodic table and the /catalyst/elements page.
 *
 * Every element carries TWO memory hooks tying its name to its symbol — many
 * symbols come from Latin/Greek names, which is exactly where a bridge is
 * needed:
 *   `esel` — the German Eselsbrücke
 *   `hook` — the English memory hook
 * Text between *asterisks* is rendered emphasized; keep the symbol's letters
 * inside the stars where possible.
 *
 * `mass` is the standard atomic weight as a display string; parenthesised
 * values are the mass number of the most stable isotope (no stable isotopes).
 * `group` is null for the f-block (lanthanides/actinides), which the grid
 * renders in the two detached rows below the main table.
 */

export type ElementCategory =
  | "alkali"
  | "alkaline"
  | "transition"
  | "post-transition"
  | "metalloid"
  | "nonmetal"
  | "halogen"
  | "noble"
  | "lanthanide"
  | "actinide"
  | "unknown";

export interface ChemElement {
  z: number;
  symbol: string;
  name: string;
  nameDe: string;
  mass: string;
  category: ElementCategory;
  period: number;
  group: number | null;
  /** Electrons per shell, innermost first — 2-8-1 for sodium. */
  shells: number[];
  /** German Eselsbrücke linking name ↔ symbol. */
  esel: string;
  /** English memory hook linking name ↔ symbol. */
  hook: string;
}

export const ELEMENTS: ChemElement[] = [
  { z: 1, symbol: "H", name: "Hydrogen", nameDe: "Wasserstoff", mass: "1.008", category: "nonmetal", period: 1, group: 1, shells: [1],
    esel: "Wasserstoff heißt lateinisch *H*ydrogenium, der ‚Wassererzeuger' — H wie Himmel: das leichteste aller Gase will immer nach oben.",
    hook: "*H*ydrogen, Greek for 'water-maker' (*hydro* + *genes*) — burn it and you get water. The lightest gas of all, forever floating up." },
  { z: 2, symbol: "He", name: "Helium", nameDe: "Helium", mass: "4.003", category: "noble", period: 1, group: 18, shells: [2],
    esel: "*He*lium wurde zuerst auf der Sonne entdeckt — benannt nach *He*lios, dem Sonnengott.",
    hook: "*He*lium was discovered on the Sun before it was found on Earth — named for *He*lios, the Greek sun god." },
  { z: 3, symbol: "Li", name: "Lithium", nameDe: "Lithium", mass: "6.94", category: "alkali", period: 2, group: 1, shells: [2, 1],
    esel: "Dein Akku *li*ebt *Li*thium — vom griechischen *líthos*, der Stein.",
    hook: "Your battery *li*ves on *Li*thium — from Greek *líthos*, 'stone', because it was found in rock rather than plants." },
  { z: 4, symbol: "Be", name: "Beryllium", nameDe: "Beryllium", mass: "9.012", category: "alkaline", period: 2, group: 2, shells: [2, 2],
    esel: "*Be*ryllium steckt im Edelstein *Be*ryll — aus dem einst die ersten ‚Brillen' geschliffen wurden.",
    hook: "*Be*ryllium hides in the gemstone *be*ryl — emeralds are beryl with a dash of chromium." },
  { z: 5, symbol: "B", name: "Boron", nameDe: "Bor", mass: "10.81", category: "metalloid", period: 2, group: 13, shells: [2, 3],
    esel: "*B*or wie *B*orax — das alte Wasch- und Putzmittel, aus dem es zuerst gewonnen wurde.",
    hook: "*B*oron as in *b*orax — the old laundry powder it was first extracted from." },
  { z: 6, symbol: "C", name: "Carbon", nameDe: "Kohlenstoff", mass: "12.011", category: "nonmetal", period: 2, group: 14, shells: [2, 4],
    esel: "Kohlenstoff heißt lateinisch *C*arboneum — wie ‚*C*arbon' im Rennrad und ‚A-*C*tivkohle' im Filter.",
    hook: "*C*arbon from Latin *c*arbo, 'charcoal' — the same C as in *c*oal, *c*harcoal and *c*arbon-fibre bikes." },
  { z: 7, symbol: "N", name: "Nitrogen", nameDe: "Stickstoff", mass: "14.007", category: "nonmetal", period: 2, group: 15, shells: [2, 5],
    esel: "Stickstoff = *N*itrogenium, der ‚Salpeterbildner'. Merksatz: *N* wie ‚*n*ix brennt' — er erstickt jede Flamme.",
    hook: "*N*itrogen, the '*n*itre-maker' (saltpetre) — remember: *N* as in '*n*othing burns', it smothers every flame." },
  { z: 8, symbol: "O", name: "Oxygen", nameDe: "Sauerstoff", mass: "15.999", category: "nonmetal", period: 2, group: 16, shells: [2, 6],
    esel: "Sauerstoff = *O*xygenium, der ‚Säurebildner' — das *O* wie in *O*xidation: ohne ihn rostet nichts und brennt nichts.",
    hook: "*O*xygen, the 'acid-maker' — the O in *o*xidation: nothing rusts and nothing burns without it." },
  { z: 9, symbol: "F", name: "Fluorine", nameDe: "Fluor", mass: "18.998", category: "halogen", period: 2, group: 17, shells: [2, 7],
    esel: "*F*luor *f*risst sogar Glas — das gierigste Element von allen, vom lateinischen *fluere*, fließen.",
    hook: "*F*luorine, from Latin *fluere*, 'to flow' — the *f*iercest element there is: it even eats glass." },
  { z: 10, symbol: "Ne", name: "Neon", nameDe: "Neon", mass: "20.180", category: "noble", period: 2, group: 18, shells: [2, 8],
    esel: "*Ne*on, griechisch ‚das *Ne*ue' — glüht orangerot in jeder klassischen Leuchtreklame.",
    hook: "*Ne*on, Greek for 'the *ne*w one' — glowing orange-red in every classic shop sign." },
  { z: 11, symbol: "Na", name: "Sodium", nameDe: "Natrium", mass: "22.990", category: "alkali", period: 3, group: 1, shells: [2, 8, 1],
    esel: "‚*Na*, Salz gefällig?' — *Na*trium steckt im Kochsalz (NaCl); der Name kommt vom ägyptischen Soda *Natron*.",
    hook: "Sodium's symbol is from its Latin name *Na*trium (Egyptian soda, *natron*) — think '*Na*Cl on your fries'." },
  { z: 12, symbol: "Mg", name: "Magnesium", nameDe: "Magnesium", mass: "24.305", category: "alkaline", period: 3, group: 2, shells: [2, 8, 2],
    esel: "*M*a*g*nesium aus der griechischen Region *Mag*nesia — brennt blendend weiß wie ein Blitzlicht.",
    hook: "*M*a*g*nesium from *Mag*nesia in Greece — burns with a blinding white flash, the original camera flashbulb." },
  { z: 13, symbol: "Al", name: "Aluminium", nameDe: "Aluminium", mass: "26.982", category: "post-transition", period: 3, group: 13, shells: [2, 8, 3],
    esel: "*Al*ufolie ist pures *Al*uminium — leichter wird Alltagsmetall nicht.",
    hook: "*Al*uminium as in *al*u-foil — everyday metal doesn't get lighter than this." },
  { z: 14, symbol: "Si", name: "Silicon", nameDe: "Silicium", mass: "28.085", category: "metalloid", period: 3, group: 14, shells: [2, 8, 4],
    esel: "*Si*licium von *si*lex, dem Feuerstein — heute rechnet jeder Chip damit: *Si*licon Valley!",
    hook: "*Si*licon from Latin *si*lex, 'flint' — today every chip computes on it: *Si*licon Valley." },
  { z: 15, symbol: "P", name: "Phosphorus", nameDe: "Phosphor", mass: "30.974", category: "nonmetal", period: 3, group: 15, shells: [2, 8, 5],
    esel: "*P*hosphor, griechisch der ‚Lichtträger' — er leuchtet im Dunkeln und zündete die ersten Streichhölzer.",
    hook: "*P*hosphorus, Greek for 'light-bearer' — it glows in the dark and struck the first matches." },
  { z: 16, symbol: "S", name: "Sulfur", nameDe: "Schwefel", mass: "32.06", category: "nonmetal", period: 3, group: 16, shells: [2, 8, 6],
    esel: "*S*chwefel wie *S*tinkbombe — lateinisch *S*ulfur: gelb, brennbar und faulig riechend.",
    hook: "*S*ulfur as in *s*tink bomb — yellow, burnable, and behind the smell of rotten eggs." },
  { z: 17, symbol: "Cl", name: "Chlorine", nameDe: "Chlor", mass: "35.45", category: "halogen", period: 3, group: 17, shells: [2, 8, 7],
    esel: "*Chl*or von *chl*ōrós, gelbgrün — das gelbgrüne Gas, das nach Schwimmbad riecht.",
    hook: "*Chl*orine from Greek *chl*ōrós, 'yellow-green' — the yellow-green gas that smells like the swimming pool." },
  { z: 18, symbol: "Ar", name: "Argon", nameDe: "Argon", mass: "39.95", category: "noble", period: 3, group: 18, shells: [2, 8, 8],
    esel: "*Ar*gon, griechisch ‚das Träge' — ‚*ar*beitsscheu' reagiert es mit rein gar nichts.",
    hook: "*Ar*gon, Greek for 'the lazy one' — it can't be *ar*sed to react with anything at all." },
  { z: 19, symbol: "K", name: "Potassium", nameDe: "Kalium", mass: "39.098", category: "alkali", period: 4, group: 1, shells: [2, 8, 8, 1],
    esel: "*K*alium wie *K*ali aus der Pflanzenasche (arabisch *al-qalya*) — nur die Engländer sagen Potassium, das Symbol bleibt K.",
    hook: "Potassium's K is from Latin *K*alium (Arabic *al-qalya*, plant ash) — remember: '*K* is in bananas… well, kalium is'." },
  { z: 20, symbol: "Ca", name: "Calcium", nameDe: "Calcium", mass: "40.078", category: "alkaline", period: 4, group: 2, shells: [2, 8, 8, 2],
    esel: "*Ca*lcium von *ca*lx, der Kalk — sitzt in Knochen, Kreide und *Ca*ppuccino-Milch.",
    hook: "*Ca*lcium from Latin *ca*lx, 'lime(stone)' — in your bones, in chalk, and in your *ca*ppuccino's milk." },
  { z: 21, symbol: "Sc", name: "Scandium", nameDe: "Scandium", mass: "44.956", category: "transition", period: 4, group: 3, shells: [2, 8, 9, 2],
    esel: "*Sc*andium wie *Sc*andinavien — dort wurde es entdeckt, genau wo Mendelejew es vorhergesagt hatte.",
    hook: "*Sc*andium as in *Sc*andinavia — discovered there, exactly where Mendeleev predicted a missing element." },
  { z: 22, symbol: "Ti", name: "Titanium", nameDe: "Titan", mass: "47.867", category: "transition", period: 4, group: 4, shells: [2, 8, 10, 2],
    esel: "*Ti*tan wie die *Ti*tanen — göttlich fest und trotzdem federleicht: das Fahrradrahmen-Metall.",
    hook: "*Ti*tanium after the *Ti*tans — divinely strong yet featherlight: the bike-frame metal." },
  { z: 23, symbol: "V", name: "Vanadium", nameDe: "Vanadium", mass: "50.942", category: "transition", period: 4, group: 5, shells: [2, 8, 11, 2],
    esel: "*V*anadium nach *V*anadis, Beiname der nordischen Göttin Freyja — seine Salze schillern göttlich bunt.",
    hook: "*V*anadium after *V*anadis, a name of the Norse goddess Freyja — its salts shimmer in divine colors." },
  { z: 24, symbol: "Cr", name: "Chromium", nameDe: "Chrom", mass: "51.996", category: "transition", period: 4, group: 6, shells: [2, 8, 13, 1],
    esel: "*Cr*/Chrom von *chr*ṓma, die Farbe — jede Oxidationsstufe leuchtet anders, und dein Wasserhahn glänzt damit.",
    hook: "*Chr*omium from Greek *chr*ōma, 'color' — every oxidation state a different hue, and your tap gleams with it." },
  { z: 25, symbol: "Mn", name: "Manganese", nameDe: "Mangan", mass: "54.938", category: "transition", period: 4, group: 7, shells: [2, 8, 13, 2],
    esel: "*M*a*n*gan = *Mn*: ‚Ma*n*gan hat das *n*, Ma*g*nesium das *g*' — so verwechselst du Mn und Mg nie wieder.",
    hook: "*M*a*n*ganese = *Mn*: 'manga*n*ese keeps the *n*, ma*g*nesium keeps the *g*' — never mix up Mn and Mg again." },
  { z: 26, symbol: "Fe", name: "Iron", nameDe: "Eisen", mass: "55.845", category: "transition", period: 4, group: 8, shells: [2, 8, 14, 2],
    esel: "Eisen heißt lateinisch *Fe*rrum — wie die *Fe*rrovia, die italienische Eisenbahn, und der *Fe*rrari aus Stahl.",
    hook: "Iron = *Fe*rrum in Latin — as in *fe*rrous metals, and a *Fe*rrari is (mostly) fancy iron." },
  { z: 27, symbol: "Co", name: "Cobalt", nameDe: "Cobalt", mass: "58.933", category: "transition", period: 4, group: 9, shells: [2, 8, 15, 2],
    esel: "*Co*balt wie der *Ko*bold, der Bergleuten ‚verhextes Erz' unterschob — dafür färbt es Glas tiefblau.",
    hook: "*Co*balt from the German *ko*bold, a mine goblin blamed for 'cursed ore' — it repays the insult by dyeing glass deep blue." },
  { z: 28, symbol: "Ni", name: "Nickel", nameDe: "Nickel", mass: "58.693", category: "transition", period: 4, group: 10, shells: [2, 8, 16, 2],
    esel: "*Ni*ckel, der zweite Bergwerks-Schelm: ‚Kupfer*ni*ckel' hieß das Erz, das partout kein Kupfer hergab.",
    hook: "*Ni*ckel, the second mine-imp: 'Old *Ni*ck's copper' was the ore that stubbornly yielded no copper at all." },
  { z: 29, symbol: "Cu", name: "Copper", nameDe: "Kupfer", mass: "63.546", category: "transition", period: 4, group: 11, shells: [2, 8, 18, 1],
    esel: "Kupfer = *Cu*prum, nach Zypern (*Cu*prus) — der Insel der antiken Kupferminen.",
    hook: "Copper = *Cu*prum, after *Cy*prus — the island of the great ancient copper mines." },
  { z: 30, symbol: "Zn", name: "Zinc", nameDe: "Zink", mass: "65.38", category: "transition", period: 4, group: 12, shells: [2, 8, 18, 2],
    esel: "*Z*i*n*k wie die *Zin*ken einer Gabel — seine Kristalle erstarren zu spitzen Zacken.",
    hook: "*Z*i*n*c from German *Zin*ke, 'prong' — its crystals freeze into jagged spikes." },
  { z: 31, symbol: "Ga", name: "Gallium", nameDe: "Gallium", mass: "69.723", category: "post-transition", period: 4, group: 13, shells: [2, 8, 18, 3],
    esel: "*Ga*llium nach *Ga*llien, dem alten Frankreich — ein Metall, das schon in deiner Handfläche schmilzt.",
    hook: "*Ga*llium after *Ga*ul (old France) — a metal that melts in the palm of your hand." },
  { z: 32, symbol: "Ge", name: "Germanium", nameDe: "Germanium", mass: "72.630", category: "metalloid", period: 4, group: 14, shells: [2, 8, 18, 4],
    esel: "*Ge*rmanium nach *Ge*rmanien — der deutsche Halbleiter, aus dem die allerersten Transistoren waren.",
    hook: "*Ge*rmanium after *Ge*rmany — the semiconductor the very first transistors were made of." },
  { z: 33, symbol: "As", name: "Arsenic", nameDe: "Arsen", mass: "74.922", category: "metalloid", period: 4, group: 15, shells: [2, 8, 18, 5],
    esel: "*As* wie *As*sassine — Arsen ist das klassische Krimigift (und schmeckt nach gar nichts, daher so beliebt).",
    hook: "*As* as in *as*sassin — arsenic is the classic whodunit poison (tasteless, hence its popularity)." },
  { z: 34, symbol: "Se", name: "Selenium", nameDe: "Selen", mass: "78.971", category: "nonmetal", period: 4, group: 16, shells: [2, 8, 18, 6],
    esel: "*Se*len nach *Se*lene, der Mondgöttin — kleiner Bruder des Tellurs, das nach der Erde heißt.",
    hook: "*Se*lenium after *Se*lene, the Moon goddess — little sibling of tellurium, which is named for the Earth." },
  { z: 35, symbol: "Br", name: "Bromine", nameDe: "Brom", mass: "79.904", category: "halogen", period: 4, group: 17, shells: [2, 8, 18, 7],
    esel: "*Br*om von *br*ōmos, der Gestank — die einzige flüssige Nichtmetall-Brühe: *br*aun, dampfend, beißend.",
    hook: "*Br*omine from Greek *br*ōmos, 'stench' — the only liquid nonmetal: *br*own, fuming and biting." },
  { z: 36, symbol: "Kr", name: "Krypton", nameDe: "Krypton", mass: "83.798", category: "noble", period: 4, group: 18, shells: [2, 8, 18, 8],
    esel: "*Kr*ypton, ‚das Verborgene' — es versteckte sich in der Luft, bis man sie destillierte. Ja, Superman lässt grüßen.",
    hook: "*Kr*ypton, Greek for 'the hidden one' — it hid in plain air until air was distilled. Yes, Superman says hi." },
  { z: 37, symbol: "Rb", name: "Rubidium", nameDe: "Rubidium", mass: "85.468", category: "alkali", period: 5, group: 1, shells: [2, 8, 18, 8, 1],
    esel: "*R*u*b*idium von *rub*idus, tiefrot — entdeckt an seinen *rub*inroten Spektrallinien.",
    hook: "*R*u*b*idium from Latin *rub*idus, 'deep red' — discovered by its *rub*y-red spectral lines." },
  { z: 38, symbol: "Sr", name: "Strontium", nameDe: "Strontium", mass: "87.62", category: "alkaline", period: 5, group: 2, shells: [2, 8, 18, 8, 2],
    esel: "*S*t*r*ontium nach dem schottischen Dorf *Str*ontian — färbt jedes Feuerwerk knallrot.",
    hook: "*S*t*r*ontium after the Scottish village of *Str*ontian — it paints fireworks crimson." },
  { z: 39, symbol: "Y", name: "Yttrium", nameDe: "Yttrium", mass: "88.906", category: "transition", period: 5, group: 3, shells: [2, 8, 18, 9, 2],
    esel: "*Y*ttrium nach *Y*tterby in Schweden — die eine Dorfgrube, die gleich vier Elementen den Namen gab (Y, Tb, Er, Yb).",
    hook: "*Y*ttrium after *Y*tterby in Sweden — the one village quarry that named four elements (Y, Tb, Er, Yb)." },
  { z: 40, symbol: "Zr", name: "Zirconium", nameDe: "Zirconium", mass: "91.224", category: "transition", period: 5, group: 4, shells: [2, 8, 18, 10, 2],
    esel: "*Zr* wie *Zir*konia — der ‚falsche Diamant' am Ringfinger ist Zirconium-Oxid.",
    hook: "*Zr* as in cubic *zir*conia — the 'faux diamond' on the ring finger is zirconium oxide." },
  { z: 41, symbol: "Nb", name: "Niobium", nameDe: "Niob", mass: "92.906", category: "transition", period: 5, group: 5, shells: [2, 8, 18, 12, 1],
    esel: "*N*io*b* nach *N*io*b*e, der Tochter des Tantalos — im Periodensystem steht es direkt über Papa Tantal.",
    hook: "*N*io*b*ium after *N*io*b*e, daughter of Tantalus — it sits right above dad tantalum in the table." },
  { z: 42, symbol: "Mo", name: "Molybdenum", nameDe: "Molybdän", mass: "95.95", category: "transition", period: 5, group: 6, shells: [2, 8, 18, 13, 1],
    esel: "*Mo*lybdän von *mó*lybdos, Blei — sein Erz wurde ewig mit Bleiglanz verwechselt.",
    hook: "*Mo*lybdenum from Greek *mó*lybdos, 'lead' — its ore was mistaken for lead ore for centuries." },
  { z: 43, symbol: "Tc", name: "Technetium", nameDe: "Technetium", mass: "(98)", category: "transition", period: 5, group: 7, shells: [2, 8, 18, 13, 2],
    esel: "*T*e*c*hnetium von *t*é*c*hnē, Kunst/Handwerk — das erste künstlich erzeugte Element: Chemie aus dem Teilchenbeschleuniger.",
    hook: "*T*e*c*hnetium from Greek *t*é*c*hnē, 'craft' — the first artificial ('technical') element, made in a particle accelerator." },
  { z: 44, symbol: "Ru", name: "Ruthenium", nameDe: "Ruthenium", mass: "101.07", category: "transition", period: 5, group: 8, shells: [2, 8, 18, 15, 1],
    esel: "*Ru*thenium nach *Ru*thenia, dem lateinischen Namen für Russland — entdeckt in Kasan.",
    hook: "*Ru*thenium after *Ru*thenia, the Latin name for *Ru*ssia — discovered in Kazan." },
  { z: 45, symbol: "Rh", name: "Rhodium", nameDe: "Rhodium", mass: "102.906", category: "transition", period: 5, group: 9, shells: [2, 8, 18, 16, 1],
    esel: "*Rh*odium von *rh*ódon, die Rose — rosarote Salze; heute glänzt es im Autokatalysator.",
    hook: "*Rh*odium from Greek *rh*ódon, 'rose' — rose-pink salts; today it shines in your car's catalytic converter." },
  { z: 46, symbol: "Pd", name: "Palladium", nameDe: "Palladium", mass: "106.42", category: "transition", period: 5, group: 10, shells: [2, 8, 18, 18],
    esel: "*P*alla*d*ium nach dem Asteroiden *P*allas — Element und Asteroid wurden fast gleichzeitig entdeckt.",
    hook: "*P*alla*d*ium after the asteroid *P*allas — element and asteroid were discovered almost together." },
  { z: 47, symbol: "Ag", name: "Silver", nameDe: "Silber", mass: "107.868", category: "transition", period: 5, group: 11, shells: [2, 8, 18, 18, 1],
    esel: "Silber = *A*r*g*entum — denk an *A*r*g*entinien, das nach dem Silber seiner Flüsse benannte Land.",
    hook: "Silver = *A*r*g*entum in Latin — think *A*r*g*entina, the country named after the silver of its rivers." },
  { z: 48, symbol: "Cd", name: "Cadmium", nameDe: "Cadmium", mass: "112.414", category: "transition", period: 5, group: 12, shells: [2, 8, 18, 18, 2],
    esel: "*C*a*d*mium nach *K*a*d*mos, dem Gründer Thebens — es versteckte sich im Zinkerz namens *cadmea* (Galmei).",
    hook: "*C*a*d*mium after *C*a*d*mus, founder of Thebes — it hid inside the zinc ore called *cadmea*." },
  { z: 49, symbol: "In", name: "Indium", nameDe: "Indium", mass: "114.818", category: "post-transition", period: 5, group: 13, shells: [2, 8, 18, 18, 3],
    esel: "*In*dium nach seiner *in*digoblauen Spektrallinie — nicht nach Indien! Dein Touchscreen leitet damit.",
    hook: "*In*dium after its *in*digo-blue spectral line — not after India! Your touchscreen conducts with it." },
  { z: 50, symbol: "Sn", name: "Tin", nameDe: "Zinn", mass: "118.710", category: "post-transition", period: 5, group: 14, shells: [2, 8, 18, 18, 4],
    esel: "Zinn = *S*ta*nn*um — wie *S*ta*nn*iol, das alte Wort für Zinnfolie um die Schokolade.",
    hook: "Tin = *S*ta*nn*um in Latin — as in *stann*ous fluoride on your toothpaste tube." },
  { z: 51, symbol: "Sb", name: "Antimony", nameDe: "Antimon", mass: "121.760", category: "metalloid", period: 5, group: 15, shells: [2, 8, 18, 18, 5],
    esel: "Antimon = *S*ti*b*ium — der antike Lidschatten: Schon Kleopatra schminkte sich mit Stibium-Pulver.",
    hook: "Antimony = *S*ti*b*ium in Latin — the ancient eyeliner: Cleopatra wore powdered stibium." },
  { z: 52, symbol: "Te", name: "Tellurium", nameDe: "Tellur", mass: "127.60", category: "metalloid", period: 5, group: 16, shells: [2, 8, 18, 18, 6],
    esel: "*Te*llur von *te*llus, die Erde — der große Bruder des Selens (Mond): Erde und Mond stehen im PSE untereinander.",
    hook: "*Te*llurium from Latin *te*llus, 'Earth' — big sibling of selenium (the Moon): Earth and Moon stacked in the table." },
  { z: 53, symbol: "I", name: "Iodine", nameDe: "Iod", mass: "126.904", category: "halogen", period: 5, group: 17, shells: [2, 8, 18, 18, 7],
    esel: "*I*od von *i*oeidḗs, veilchenfarben — erhitzt steigt es als v*i*olette Dampfwolke auf.",
    hook: "*I*odine from Greek *i*oeidḗs, 'violet-colored' — heat it and it rises as a v*i*olet vapor cloud." },
  { z: 54, symbol: "Xe", name: "Xenon", nameDe: "Xenon", mass: "131.293", category: "noble", period: 5, group: 18, shells: [2, 8, 18, 18, 8],
    esel: "*Xe*non, ‚das Fremde' — der *xe*nophobe Einzelgänger unter den Gasen, der trotzdem in *Xe*non-Scheinwerfern leuchtet.",
    hook: "*Xe*non, Greek for 'the stranger' — the aloof loner of the gases, yet it blazes in *xe*non headlights." },
  { z: 55, symbol: "Cs", name: "Caesium", nameDe: "Caesium", mass: "132.905", category: "alkali", period: 6, group: 1, shells: [2, 8, 18, 18, 8, 1],
    esel: "*C*ae*s*ium von *caes*ius, himmelblau — nach seinen blauen Spektrallinien; sein Herzschlag taktet jede Atomuhr.",
    hook: "*C*ae*s*ium from Latin *caes*ius, 'sky-blue' — named for its blue spectral lines; its heartbeat runs every atomic clock." },
  { z: 56, symbol: "Ba", name: "Barium", nameDe: "Barium", mass: "137.327", category: "alkaline", period: 6, group: 2, shells: [2, 8, 18, 18, 8, 2],
    esel: "*Ba*rium von *ba*rýs, schwer — gefunden im ‚Schwerspat', und beim Röntgen schluckst du seinen *Ba*rium-Brei.",
    hook: "*Ba*rium from Greek *ba*rýs, 'heavy' — found in 'heavy spar', and swallowed as the *ba*rium meal before an X-ray." },
  { z: 57, symbol: "La", name: "Lanthanum", nameDe: "Lanthan", mass: "138.905", category: "lanthanide", period: 6, group: null, shells: [2, 8, 18, 18, 9, 2],
    esel: "*La*nthan von *la*nthánein, ‚verborgen sein' — es versteckte sich jahrelang unentdeckt im Ceriterz.",
    hook: "*La*nthanum from Greek *la*nthánein, 'to lie hidden' — it lurked undetected in cerium ore for years." },
  { z: 58, symbol: "Ce", name: "Cerium", nameDe: "Cer", mass: "140.116", category: "lanthanide", period: 6, group: null, shells: [2, 8, 18, 19, 9, 2],
    esel: "*Ce*r nach *Ce*res, dem gerade entdeckten Zwergplaneten — der ‚Feuerstein' im Feuerzeug ist Cer-Legierung.",
    hook: "*Ce*rium after *Ce*res, the just-discovered dwarf planet — the 'flint' in your lighter is a cerium alloy." },
  { z: 59, symbol: "Pr", name: "Praseodymium", nameDe: "Praseodym", mass: "140.908", category: "lanthanide", period: 6, group: null, shells: [2, 8, 18, 21, 8, 2],
    esel: "*Pr*aseodym, der ‚lauchgrüne Zwilling' (*prásios* = lauchgrün) — seine Salze sind grün wie Lauch.",
    hook: "*Pr*aseodymium, the 'leek-green twin' (Greek *pr*ásios = leek-green) — its salts really are leek green." },
  { z: 60, symbol: "Nd", name: "Neodymium", nameDe: "Neodym", mass: "144.242", category: "lanthanide", period: 6, group: null, shells: [2, 8, 18, 22, 8, 2],
    esel: "*N*eo*d*ym, der ‚neue Zwilling' — deine stärksten Magnete sind *N*eo*d*ym-Magnete.",
    hook: "*N*eo*d*ymium, the 'new twin' — your strongest magnets are *n*eo*d*ymium magnets." },
  { z: 61, symbol: "Pm", name: "Promethium", nameDe: "Promethium", mass: "(145)", category: "lanthanide", period: 6, group: null, shells: [2, 8, 18, 23, 8, 2],
    esel: "*P*ro*m*ethium nach *P*ro*m*etheus, der das Feuer stahl — radioaktiv wie geraubtes Götterfeuer.",
    hook: "*P*ro*m*ethium after *P*ro*m*etheus, who stole fire from the gods — radioactive, like stolen divine fire should be." },
  { z: 62, symbol: "Sm", name: "Samarium", nameDe: "Samarium", mass: "150.36", category: "lanthanide", period: 6, group: null, shells: [2, 8, 18, 24, 8, 2],
    esel: "*S*a*m*arium nach Bergrat *Sam*arski — das erste Element, das je nach einer Person benannt wurde.",
    hook: "*S*a*m*arium after mining officer *Sam*arsky — the first element ever named after a person." },
  { z: 63, symbol: "Eu", name: "Europium", nameDe: "Europium", mass: "151.964", category: "lanthanide", period: 6, group: null, shells: [2, 8, 18, 25, 8, 2],
    esel: "*Eu*ropium nach *Eu*ropa — es leuchtete rot im Röhrenfernseher und leuchtet heute als Fälschungsschutz im *Eu*ro-Schein.",
    hook: "*Eu*ropium after *Eu*rope — it glowed red in CRT televisions and now glows in *eu*ro banknotes as an anti-forgery mark." },
  { z: 64, symbol: "Gd", name: "Gadolinium", nameDe: "Gadolinium", mass: "157.25", category: "lanthanide", period: 6, group: null, shells: [2, 8, 18, 25, 9, 2],
    esel: "*G*a*d*olinium nach Johan *G*a*d*olin, dem Ytterby-Pionier — das Kontrastmittel im MRT.",
    hook: "*G*a*d*olinium after Johan *G*a*d*olin, the Ytterby pioneer — the contrast agent in MRI scans." },
  { z: 65, symbol: "Tb", name: "Terbium", nameDe: "Terbium", mass: "158.925", category: "lanthanide", period: 6, group: null, shells: [2, 8, 18, 27, 8, 2],
    esel: "*T*er*b*ium — Ytterby-Kind Nr. 2: nimm Yt*terb*y und streich das ‚Yt' vorne weg.",
    hook: "*T*er*b*ium — Ytterby child no. 2: take Yt*terb*y and drop the 'Yt'." },
  { z: 66, symbol: "Dy", name: "Dysprosium", nameDe: "Dysprosium", mass: "162.500", category: "lanthanide", period: 6, group: null, shells: [2, 8, 18, 28, 8, 2],
    esel: "*Dy*sprosium von *dy*sprósitos, ‚schwer beizukommen' — es ließ sich jahrzehntelang nicht rein isolieren.",
    hook: "*Dy*sprosium from Greek *dy*sprósitos, 'hard to get at' — it resisted clean isolation for decades." },
  { z: 67, symbol: "Ho", name: "Holmium", nameDe: "Holmium", mass: "164.930", category: "lanthanide", period: 6, group: null, shells: [2, 8, 18, 29, 8, 2],
    esel: "*Ho*lmium nach Stock*ho*lm — der Heimatstadt seiner Entdecker.",
    hook: "*Ho*lmium after Stock*ho*lm — its discoverers' home town." },
  { z: 68, symbol: "Er", name: "Erbium", nameDe: "Erbium", mass: "167.259", category: "lanthanide", period: 6, group: null, shells: [2, 8, 18, 30, 8, 2],
    esel: "*Er*bium — Ytterby-Kind Nr. 3: die Mitte von Ytt*er*by. Es verstärkt das Licht in Glasfaserkabeln.",
    hook: "*Er*bium — Ytterby child no. 3: the middle of Ytt*er*by. It amplifies the light in fibre-optic cables." },
  { z: 69, symbol: "Tm", name: "Thulium", nameDe: "Thulium", mass: "168.934", category: "lanthanide", period: 6, group: null, shells: [2, 8, 18, 31, 8, 2],
    esel: "*T*huliu*m* nach *T*hule, dem sagenhaften Land im hohen Norden — das seltenste stabile Seltenerdmetall.",
    hook: "*T*huliu*m* after *T*hule, the mythical land of the far north — the rarest of the stable rare earths." },
  { z: 70, symbol: "Yb", name: "Ytterbium", nameDe: "Ytterbium", mass: "173.045", category: "lanthanide", period: 6, group: null, shells: [2, 8, 18, 32, 8, 2],
    esel: "*Y*tter*b*ium — Ytterby-Kind Nr. 4: diesmal blieb fast der ganze Dorfname dran.",
    hook: "*Y*tter*b*ium — Ytterby child no. 4: this time nearly the whole village name stuck." },
  { z: 71, symbol: "Lu", name: "Lutetium", nameDe: "Lutetium", mass: "174.967", category: "lanthanide", period: 6, group: null, shells: [2, 8, 18, 32, 9, 2],
    esel: "*Lu*tetium nach *Lu*tetia, dem römischen Namen von Paris — das letzte, härteste Lanthanoid.",
    hook: "*Lu*tetium after *Lu*tetia, the Roman name of Paris — the last and hardest lanthanide." },
  { z: 72, symbol: "Hf", name: "Hafnium", nameDe: "Hafnium", mass: "178.486", category: "transition", period: 6, group: 4, shells: [2, 8, 18, 32, 10, 2],
    esel: "*H*a*f*nium nach *Haf*nia, dem lateinischen Kopenhagen — entdeckt in Niels Bohrs Institut.",
    hook: "*H*a*f*nium after *Haf*nia, Latin for Copenhagen — discovered at Niels Bohr's institute." },
  { z: 73, symbol: "Ta", name: "Tantalum", nameDe: "Tantal", mass: "180.948", category: "transition", period: 6, group: 5, shells: [2, 8, 18, 32, 11, 2],
    esel: "*Ta*ntal nach *Ta*ntalos, der ewig dürstet — das Metall ‚trinkt' keine Säure, und im Handy sitzt es als Kondensator.",
    hook: "*Ta*ntalum after *Ta*ntalus, forever thirsty — the metal 'drinks' no acid at all, and sits in your phone as a capacitor." },
  { z: 74, symbol: "W", name: "Tungsten", nameDe: "Wolfram", mass: "183.84", category: "transition", period: 6, group: 6, shells: [2, 8, 18, 32, 12, 2],
    esel: "*W*olfram — ein deutsches Wort im Weltvokabular! Englisch heißt es Tungsten, das Symbol bleibt trotzdem *W*: der Glühdraht der alten Glühbirne.",
    hook: "Tungsten's W is from *W*olfram, its German name ('wolf's cream', the ore that 'devoured' tin) — the glow-wire of the old light bulb." },
  { z: 75, symbol: "Re", name: "Rhenium", nameDe: "Rhenium", mass: "186.207", category: "transition", period: 6, group: 7, shells: [2, 8, 18, 32, 13, 2],
    esel: "*R*h*e*nium nach dem *R*h*e*in — eines der letzten stabilen Elemente, die je entdeckt wurden (1925, in Berlin).",
    hook: "*R*h*e*nium after the river *R*hine (*Rhe*nus) — one of the last stable elements ever discovered (1925, Berlin)." },
  { z: 76, symbol: "Os", name: "Osmium", nameDe: "Osmium", mass: "190.23", category: "transition", period: 6, group: 8, shells: [2, 8, 18, 32, 14, 2],
    esel: "*Os*mium von *os*mḗ, der Geruch — sein Oxid stinkt beißend, und kein Metall ist dichter.",
    hook: "*Os*mium from Greek *os*mḗ, 'smell' — its oxide reeks, and no metal is denser." },
  { z: 77, symbol: "Ir", name: "Iridium", nameDe: "Iridium", mass: "192.217", category: "transition", period: 6, group: 9, shells: [2, 8, 18, 32, 15, 2],
    esel: "*Ir*idium nach *Ir*is, der Regenbogengöttin — und eine dünne Iridium-Staubschicht im Gestein verrät den Dino-Killer-Asteroiden.",
    hook: "*Ir*idium after *Ir*is, goddess of the rainbow — and a thin iridium dust layer in the rocks betrays the dino-killer asteroid." },
  { z: 78, symbol: "Pt", name: "Platinum", nameDe: "Platin", mass: "195.084", category: "transition", period: 6, group: 10, shells: [2, 8, 18, 32, 17, 1],
    esel: "*P*la*t*in von spanisch *plata*, Silber — ‚*plat*ina', Silberchen, spotteten die Konquistadoren. Heute ist es teurer als Gold.",
    hook: "*P*la*t*inum from Spanish *plat*a, 'silver' — '*plat*ina', 'little silver', the conquistadors sneered. Now it outprices gold." },
  { z: 79, symbol: "Au", name: "Gold", nameDe: "Gold", mass: "196.967", category: "transition", period: 6, group: 11, shells: [2, 8, 18, 32, 18, 1],
    esel: "Gold = *Au*rum, verwandt mit *Au*rora, der Morgenröte — Merkhilfe: ‚*Au*! Mein Goldzahn!'",
    hook: "Gold = *Au*rum in Latin, kin to *Au*rora, the dawn glow — memory aid: '*Au*! Someone stole my gold tooth!'" },
  { z: 80, symbol: "Hg", name: "Mercury", nameDe: "Quecksilber", mass: "200.592", category: "transition", period: 6, group: 12, shells: [2, 8, 18, 32, 18, 2],
    esel: "Quecksilber = *H*ydrar*g*yrum, ‚Wassersilber' (*hydro* + *argyros*) — das einzige Metall, das bei Raumtemperatur flüssig ist.",
    hook: "Mercury = *H*ydrar*g*yrum, 'water-silver' (Greek *hydro* + *argyros*) — the only metal that's liquid at room temperature." },
  { z: 81, symbol: "Tl", name: "Thallium", nameDe: "Thallium", mass: "204.38", category: "post-transition", period: 6, group: 13, shells: [2, 8, 18, 32, 18, 3],
    esel: "*T*ha*ll*ium von *tha*llós, der grüne Spross — entdeckt an einer grasgrünen Spektrallinie; berüchtigt als Gift.",
    hook: "*T*ha*ll*ium from Greek *tha*llós, 'green shoot' — found by its grass-green spectral line; infamous as a poison." },
  { z: 82, symbol: "Pb", name: "Lead", nameDe: "Blei", mass: "207.2", category: "post-transition", period: 6, group: 14, shells: [2, 8, 18, 32, 18, 4],
    esel: "Blei = *P*lum*b*um — daher der englische ‚*P*lum*b*er': Klempner verlegten einst Bleirohre.",
    hook: "Lead = *P*lum*b*um in Latin — hence the *p*lum*b*er, who once laid lead pipes." },
  { z: 83, symbol: "Bi", name: "Bismuth", nameDe: "Bismut", mass: "208.980", category: "post-transition", period: 6, group: 15, shells: [2, 8, 18, 32, 18, 5],
    esel: "*Bi*smut wächst zu *bi*zarren, regenbogenbunten Treppenkristallen — das schwerste (praktisch) stabile Element.",
    hook: "*Bi*smuth grows *bi*zarre rainbow staircase crystals — the heaviest (practically) stable element." },
  { z: 84, symbol: "Po", name: "Polonium", nameDe: "Polonium", mass: "(209)", category: "post-transition", period: 6, group: 16, shells: [2, 8, 18, 32, 18, 6],
    esel: "*Po*lonium nach *Po*len — Marie Curie taufte ihr erstes Element auf ihre Heimat.",
    hook: "*Po*lonium after *Po*land — Marie Curie named her first element for her homeland." },
  { z: 85, symbol: "At", name: "Astatine", nameDe: "Astat", mass: "(210)", category: "halogen", period: 6, group: 17, shells: [2, 8, 18, 32, 18, 7],
    esel: "*A*sta*t* von *a*statos, ‚unbeständig' — das seltenste natürliche Element: Weltweit existiert davon nur etwa ein Gramm.",
    hook: "*A*sta*t*ine from Greek *a*statos, 'unstable' — the rarest natural element: about one gram exists on Earth at any time." },
  { z: 86, symbol: "Rn", name: "Radon", nameDe: "Radon", mass: "(222)", category: "noble", period: 6, group: 18, shells: [2, 8, 18, 32, 18, 8],
    esel: "*R*ado*n* — des *R*adiums flüchtiger Sohn: das radioaktive Edelgas, das aus Granitkellern kriecht.",
    hook: "*R*ado*n* — *r*adium's fugitive son: the radioactive noble gas that seeps out of granite basements." },
  { z: 87, symbol: "Fr", name: "Francium", nameDe: "Francium", mass: "(223)", category: "alkali", period: 7, group: 1, shells: [2, 8, 18, 32, 18, 8, 1],
    esel: "*Fr*ancium nach *Fr*ankreich — entdeckt von Marguerite Perey, Marie Curies Schülerin.",
    hook: "*Fr*ancium after *Fr*ance — discovered by Marguerite Perey, Marie Curie's student." },
  { z: 88, symbol: "Ra", name: "Radium", nameDe: "Radium", mass: "(226)", category: "alkaline", period: 7, group: 2, shells: [2, 8, 18, 32, 18, 8, 2],
    esel: "*Ra*dium von *ra*dius, der Strahl — die Curies kochten es aus Tonnen Pechblende; es glimmt von selbst.",
    hook: "*Ra*dium from Latin *ra*dius, 'ray' — the Curies boiled it out of tons of pitchblende; it glows on its own." },
  { z: 89, symbol: "Ac", name: "Actinium", nameDe: "Actinium", mass: "(227)", category: "actinide", period: 7, group: null, shells: [2, 8, 18, 32, 18, 9, 2],
    esel: "*Ac*tinium von *ak*tís, der Strahl — Namenspate der ganzen *Ac*tinoiden-Reihe.",
    hook: "*Ac*tinium from Greek *ak*tís, 'ray' — godparent to the whole *ac*tinide row." },
  { z: 90, symbol: "Th", name: "Thorium", nameDe: "Thorium", mass: "232.038", category: "actinide", period: 7, group: null, shells: [2, 8, 18, 32, 18, 10, 2],
    esel: "*Th*orium nach *Th*or, dem Donnergott — Kernbrennstoff mit Hammer-Namen.",
    hook: "*Th*orium after *Th*or, god of thunder — nuclear fuel with a hammer of a name." },
  { z: 91, symbol: "Pa", name: "Protactinium", nameDe: "Protactinium", mass: "231.036", category: "actinide", period: 7, group: null, shells: [2, 8, 18, 32, 20, 9, 2],
    esel: "*P*rot*a*ctinium, das ‚Ur-Actinium' — beim Zerfall wird es selbst zu Actinium.",
    hook: "*P*rot*a*ctinium, the 'proto-actinium' — it decays into actinium itself." },
  { z: 92, symbol: "U", name: "Uranium", nameDe: "Uran", mass: "238.029", category: "actinide", period: 7, group: null, shells: [2, 8, 18, 32, 21, 9, 2],
    esel: "*U*ran nach dem Planeten *U*ranus — benannt acht Jahre nach dessen Entdeckung.",
    hook: "*U*ranium after the planet *U*ranus — named eight years after the planet was found." },
  { z: 93, symbol: "Np", name: "Neptunium", nameDe: "Neptunium", mass: "(237)", category: "actinide", period: 7, group: null, shells: [2, 8, 18, 32, 22, 9, 2],
    esel: "*N*e*p*tunium nach Ne*p*tun — im Sonnensystem wie im Periodensystem gleich hinter Uran(us).",
    hook: "*N*e*p*tunium after Ne*p*tune — right after Uran(us), in the solar system and the periodic table alike." },
  { z: 94, symbol: "Pu", name: "Plutonium", nameDe: "Plutonium", mass: "(244)", category: "actinide", period: 7, group: null, shells: [2, 8, 18, 32, 24, 8, 2],
    esel: "*P*l*u*tonium nach *P*l*u*to — die Reihe Uranus–Neptun–Pluto läuft im Periodensystem einfach weiter.",
    hook: "*P*l*u*tonium after *P*l*u*to — the Uranus–Neptune–Pluto sequence just keeps going in the table." },
  { z: 95, symbol: "Am", name: "Americium", nameDe: "Americium", mass: "(243)", category: "actinide", period: 7, group: null, shells: [2, 8, 18, 32, 25, 8, 2],
    esel: "*Am*ericium nach *Am*erika — analog zum Europium eine Zeile höher; es wacht in deinem Rauchmelder.",
    hook: "*Am*ericium after *Am*erica — the counterpart of europium one row up; it keeps watch inside your smoke detector." },
  { z: 96, symbol: "Cm", name: "Curium", nameDe: "Curium", mass: "(247)", category: "actinide", period: 7, group: null, shells: [2, 8, 18, 32, 25, 9, 2],
    esel: "*C*uriu*m* nach *M*arie und Pierre *C*urie — ein Element für das Ehepaar der Radioaktivität.",
    hook: "*C*uriu*m* after *M*arie and Pierre *C*urie — one element for radioactivity's power couple." },
  { z: 97, symbol: "Bk", name: "Berkelium", nameDe: "Berkelium", mass: "(247)", category: "actinide", period: 7, group: null, shells: [2, 8, 18, 32, 27, 8, 2],
    esel: "*B*er*k*elium nach *B*er*k*eley — der kalifornischen Elementfabrik der 1950er.",
    hook: "*B*er*k*elium after *B*er*k*eley — the Californian element factory of the 1950s." },
  { z: 98, symbol: "Cf", name: "Californium", nameDe: "Californium", mass: "(251)", category: "actinide", period: 7, group: null, shells: [2, 8, 18, 32, 28, 8, 2],
    esel: "*C*ali*f*ornium nach *C*ali*f*ornien — Nachbar von Berkelium, im Labor wie auf der Landkarte.",
    hook: "*C*ali*f*ornium after *C*ali*f*ornia — berkelium's neighbour, in the lab and on the map." },
  { z: 99, symbol: "Es", name: "Einsteinium", nameDe: "Einsteinium", mass: "(252)", category: "actinide", period: 7, group: null, shells: [2, 8, 18, 32, 29, 8, 2],
    esel: "*E*in*s*teinium nach Albert *E*in*s*tein — aufgespürt im Fallout des ersten Wasserstoffbomben-Tests.",
    hook: "*E*in*s*teinium after Albert *E*in*s*tein — first spotted in the fallout of the first hydrogen-bomb test." },
  { z: 100, symbol: "Fm", name: "Fermium", nameDe: "Fermium", mass: "(257)", category: "actinide", period: 7, group: null, shells: [2, 8, 18, 32, 30, 8, 2],
    esel: "*F*er*m*ium nach Enrico *F*er*m*i — dem Baumeister des ersten Kernreaktors.",
    hook: "*F*er*m*ium after Enrico *F*er*m*i — builder of the first nuclear reactor." },
  { z: 101, symbol: "Md", name: "Mendelevium", nameDe: "Mendelevium", mass: "(258)", category: "actinide", period: 7, group: null, shells: [2, 8, 18, 32, 31, 8, 2],
    esel: "*M*en*d*elevium nach *M*en*d*elejew — dem Vater des Periodensystems höchstpersönlich.",
    hook: "*M*en*d*elevium after *M*en*d*eleev — the father of the periodic table himself." },
  { z: 102, symbol: "No", name: "Nobelium", nameDe: "Nobelium", mass: "(259)", category: "actinide", period: 7, group: null, shells: [2, 8, 18, 32, 32, 8, 2],
    esel: "*No*belium nach Alfred *No*bel — Dynamit-Erfinder und Preisstifter.",
    hook: "*No*belium after Alfred *No*bel — dynamite inventor, prize founder." },
  { z: 103, symbol: "Lr", name: "Lawrencium", nameDe: "Lawrencium", mass: "(266)", category: "actinide", period: 7, group: null, shells: [2, 8, 18, 32, 32, 8, 3],
    esel: "*L*aw*r*encium nach Ernest *L*aw*r*ence — dem Erfinder des Zyklotrons, das solche Elemente überhaupt erst erzeugt.",
    hook: "*L*aw*r*encium after Ernest *L*aw*r*ence — inventor of the cyclotron, the machine that makes such elements possible." },
  { z: 104, symbol: "Rf", name: "Rutherfordium", nameDe: "Rutherfordium", mass: "(267)", category: "transition", period: 7, group: 4, shells: [2, 8, 18, 32, 32, 10, 2],
    esel: "*R*uther*f*ordium nach *R*uther*f*ord — dem Mann, der den Atomkern entdeckte.",
    hook: "*R*uther*f*ordium after *R*uther*f*ord — the man who discovered the atomic nucleus." },
  { z: 105, symbol: "Db", name: "Dubnium", nameDe: "Dubnium", mass: "(268)", category: "transition", period: 7, group: 5, shells: [2, 8, 18, 32, 32, 11, 2],
    esel: "*D*u*b*nium nach *D*u*b*na — dem russischen Gegenstück zur Elementküche in Berkeley.",
    hook: "*D*u*b*nium after *D*u*b*na — Russia's answer to the Berkeley element kitchen." },
  { z: 106, symbol: "Sg", name: "Seaborgium", nameDe: "Seaborgium", mass: "(269)", category: "transition", period: 7, group: 6, shells: [2, 8, 18, 32, 32, 12, 2],
    esel: "*S*eabor*g*ium nach Glenn *S*eabor*g* — benannt zu Lebzeiten: Man hätte ihm Post ‚an sein Element' schicken können.",
    hook: "*S*eabor*g*ium after Glenn *S*eabor*g* — named while he was alive: you could have mailed him a letter 'at his element'." },
  { z: 107, symbol: "Bh", name: "Bohrium", nameDe: "Bohrium", mass: "(270)", category: "transition", period: 7, group: 7, shells: [2, 8, 18, 32, 32, 13, 2],
    esel: "*B*o*h*rium nach Niels *B*o*h*r — dem Vater des Schalenmodells aus Lektion 0.2.",
    hook: "*B*o*h*rium after Niels *B*o*h*r — father of the shell model from lesson 0.2." },
  { z: 108, symbol: "Hs", name: "Hassium", nameDe: "Hassium", mass: "(277)", category: "transition", period: 7, group: 8, shells: [2, 8, 18, 32, 32, 14, 2],
    esel: "*H*a*s*sium nach He*ss*en (lateinisch *Hass*ia) — erzeugt bei der GSI in Darmstadt.",
    hook: "*H*a*s*sium after He*ss*e, the German state (Latin *Hass*ia) — forged at the GSI lab in Darmstadt." },
  { z: 109, symbol: "Mt", name: "Meitnerium", nameDe: "Meitnerium", mass: "(278)", category: "unknown", period: 7, group: 9, shells: [2, 8, 18, 32, 32, 15, 2],
    esel: "*M*ei*t*nerium nach Lise *M*ei*t*ner — der Erklärerin der Kernspaltung, der der Nobelpreis verwehrt blieb. Das Element nicht.",
    hook: "*M*ei*t*nerium after Lise *M*ei*t*ner — who explained nuclear fission and was denied the Nobel. Not the element, though." },
  { z: 110, symbol: "Ds", name: "Darmstadtium", nameDe: "Darmstadtium", mass: "(281)", category: "unknown", period: 7, group: 10, shells: [2, 8, 18, 32, 32, 16, 2],
    esel: "*D*arm*s*tadtium nach *D*arm*s*tadt — made in Germany, Atom für Atom.",
    hook: "*D*arm*s*tadtium after *D*arm*s*tadt — made in Germany, one atom at a time." },
  { z: 111, symbol: "Rg", name: "Roentgenium", nameDe: "Roentgenium", mass: "(282)", category: "unknown", period: 7, group: 11, shells: [2, 8, 18, 32, 32, 17, 2],
    esel: "*R*oent*g*enium nach Wilhelm *R*önt*g*en — dem Entdecker der X-Strahlen, die bei uns seinen Namen tragen.",
    hook: "*R*oent*g*enium after Wilhelm *R*önt*g*en — discoverer of X-rays (called Röntgen rays in German)." },
  { z: 112, symbol: "Cn", name: "Copernicium", nameDe: "Copernicium", mass: "(285)", category: "unknown", period: 7, group: 12, shells: [2, 8, 18, 32, 32, 18, 2],
    esel: "*C*oper*n*icium nach *C*oper*n*icus (Kopernikus) — der die Sonne ins Zentrum rückte.",
    hook: "*C*oper*n*icium after *C*oper*n*icus — who put the Sun at the centre." },
  { z: 113, symbol: "Nh", name: "Nihonium", nameDe: "Nihonium", mass: "(286)", category: "unknown", period: 7, group: 13, shells: [2, 8, 18, 32, 32, 18, 3],
    esel: "*N*i*h*onium nach *N*i*h*on, Japan — das erste in Asien erzeugte Element.",
    hook: "*N*i*h*onium after *N*i*h*on — 'Japan' in Japanese: the first element created in Asia." },
  { z: 114, symbol: "Fl", name: "Flerovium", nameDe: "Flerovium", mass: "(289)", category: "unknown", period: 7, group: 14, shells: [2, 8, 18, 32, 32, 18, 4],
    esel: "*Fl*erovium nach Georgi *Fl*jorow — dem Gründer des Dubna-Labors.",
    hook: "*Fl*erovium after Georgy *Fl*yorov — founder of the Dubna lab." },
  { z: 115, symbol: "Mc", name: "Moscovium", nameDe: "Moscovium", mass: "(290)", category: "unknown", period: 7, group: 15, shells: [2, 8, 18, 32, 32, 18, 5],
    esel: "*M*os*c*ovium nach *M*oskau (*Mosc*ow) — der Oblast, in der Dubna liegt.",
    hook: "*M*os*c*ovium after *Mosc*ow — the oblast that Dubna calls home." },
  { z: 116, symbol: "Lv", name: "Livermorium", nameDe: "Livermorium", mass: "(293)", category: "unknown", period: 7, group: 16, shells: [2, 8, 18, 32, 32, 18, 6],
    esel: "*L*i*v*ermorium nach dem *L*i*v*ermore-Labor in Kalifornien — Dubnas amerikanischem Partner.",
    hook: "*L*i*v*ermorium after the *L*i*v*ermore lab in California — Dubna's American partner." },
  { z: 117, symbol: "Ts", name: "Tennessine", nameDe: "Tenness", mass: "(294)", category: "unknown", period: 7, group: 17, shells: [2, 8, 18, 32, 32, 18, 7],
    esel: "*T*enne*ss* nach *T*enne*ss*ee — dem Bundesstaat des Oak-Ridge-Labors, das das Zielmaterial lieferte.",
    hook: "*T*enne*ss*ine after *T*enne*ss*ee — home state of the Oak Ridge lab that supplied the target material." },
  { z: 118, symbol: "Og", name: "Oganesson", nameDe: "Oganesson", mass: "(294)", category: "unknown", period: 7, group: 18, shells: [2, 8, 18, 32, 32, 18, 8],
    esel: "*Og*anesson nach Juri *Og*anessjan — erst der zweite Mensch, der sein eigenes Element im Periodensystem stehen sah.",
    hook: "*Og*anesson after Yuri *Og*anessian — only the second person ever to see their own element enter the table in their lifetime." },
];

export function elementBySymbol(symbol: string): ChemElement | undefined {
  return ELEMENTS.find((e) => e.symbol === symbol);
}

/** CSS custom-property name for a category's color (defined in globals.css). */
export function categoryVar(cat: ElementCategory): string {
  return `var(--cat-${cat})`;
}
