/**
 * Exact-match EN→DE dictionary for Servo's interactive labs (canvas labels,
 * meter titles, control labels, in-lab buttons) — the same mechanism the other
 * courses use.
 *
 * The canvas is not React, so it cannot read the language context; instead the
 * LanguageProvider calls setLabDictionary() on every switch and the drawing
 * primitives translate through tl(). Keys must match the source strings
 * character-exactly. Dynamic strings (template literals with numbers) fall
 * through untranslated by design — they are mostly numbers and units.
 */

export const LAB_DE: Record<string, string> = {
  /* ---- shared control vocabulary ---- */
  Time: "Zeit",
  Speed: "Tempo",
  speed: "Tempo",
  torque: "Drehmoment",
  Load: "Last",
  target: "Ziel",
  Rule: "Regel",
  Formula: "Formel",
  Note: "Hinweis",
  Try: "Probier",
  Recipe: "Rezept",
  Cure: "Heilmittel",
  Pattern: "Muster",
  Trade: "Tausch",
  State: "Zustand",
  Verdict: "Urteil",
  and: "und",
  of: "von",
  to: "bis",
  over: "bei",
  across: "über",
  worlds: "Welten",
  forward: "vorwärts",
  reverse: "rückwärts",
  none: "keins",
  running: "läuft",
  never: "nie",
  turn: "drehen",
  honest: "ehrlich",

  /* ---- unit 0: the loop ---- */
  "the wall": "die Wand",
  "stop line": "Stopplinie",
  "this run": "dieser Lauf",
  CRASH: "CRASH",
  "sensed too late to brake": "zu spät gemessen, um zu bremsen",
  "stopped short of the wall": "vor der Wand zum Stehen gekommen",
  "loop period": "Schleifenperiode",
  "blind distance / loop": "Blindstrecke / Schleife",
  "Loop rate": "Schleifenrate",
  "Stop distance": "Stoppabstand",
  "Stop margin": "Stopp-Reserve",
  crashed: "gecrasht",
  "Worst-case overshoot": "Überschwingen im schlimmsten Fall",
  "a slow loop drives blind between samples": "eine langsame Schleife fährt zwischen den Messungen blind",
  average: "Mittelwert",
  "one cycle": "ein Zyklus",
  motor: "Motor",
  "Duty cycle": "Tastgrad",
  Frequency: "Frequenz",
  "Average voltage": "Mittlere Spannung",
  LED: "LED",
  "strobing — eye can follow the pulses": "stroboskopiert — das Auge kann den Pulsen folgen",
  "steady to the eye": "fürs Auge ruhig",
  Motor: "Motor",
  "lumpy — inertia can't smooth this": "ruckelig — die Trägheit glättet das nicht mehr",
  "smooth — rides the average": "glatt — reitet auf dem Mittelwert",
  "average voltage": "mittlere Spannung",
  duty: "Tastgrad",
  "motor ripple": "Motor-Welligkeit",

  /* ---- unit 1: motors ---- */
  "STALL — all heat, no motion": "BLOCKIERT — nur Hitze, keine Bewegung",
  "H-bridge": "H-Brücke",
  "power rail": "Versorgungsschiene",
  "battery under load": "Akku unter Last",
  "brain: brown-out!": "Gehirn: Brown-out!",
  "brain: happy": "Gehirn: zufrieden",
  current: "Strom",
  "torque demand": "Momentbedarf",
  "PWM duty": "PWM-Tastgrad",
  "Mechanical load": "Mechanische Last",
  Direction: "Richtung",
  "stalled — current maxed, speed zero": "blockiert — Strom am Anschlag, Tempo null",
  "Battery sag": "Akku-Einbruch",
  "volts set speed, load sets current": "Volt setzen das Tempo, Last den Strom",
  "fan mood": "Lüfter-Laune",
  servo: "Servo",
  stepper: "Schrittmotor",
  "its own belief": "sein eigener Glaube",
  "the books": "die Bücher",
  "servo error": "Servo-Fehler",
  "stepper error": "Schrittmotor-Fehler",
  "and it doesn't know": "und er weiß es nicht",
  "off — and it doesn't know": "daneben — und er weiß es nicht",
  "honest (so far)": "ehrlich (bisher)",
  "Commanded angle": "Befohlener Winkel",
  Disturb: "Stören",
  "💥 Shove both": "💥 Beide schubsen",
  "🏠 Re-home stepper": "🏠 Schrittmotor re-homen",
  Servo: "Servo",
  "fights back — its loop closes on the truth": "wehrt sich — seine Schleife schließt auf die Wahrheit",
  "Stepper belief vs reality": "Schrittmotor: Glaube vs. Wirklichkeit",
  "Last move skipped": "Beim letzten Zug übersprungen",
  "motor gear": "Motor-Zahnrad",
  "output gear": "Abtriebs-Zahnrad",
  "backlash: crossing the gap": "Spiel: die Lücke wird durchquert",
  "the load": "die Last",
  lifting: "hebt",
  "too heavy — stalled": "zu schwer — blockiert",
  "output speed": "Abtriebsdrehzahl",
  "output torque": "Abtriebsmoment",
  "friction fee": "Reibungsgebühr",
  "Gear ratio": "Übersetzung",
  "Load torque": "Lastmoment",
  Backlash: "Spiel (Backlash)",
  "lifts it": "hebt sie",
  "stalls — gear down further": "blockiert — weiter untersetzen",
  "Dead zone on reversal": "Totzone beim Richtungswechsel",

  /* ---- unit 2: senses ---- */
  ultrasonic: "Ultraschall",
  laser: "Laser",
  "reflected away": "weggespiegelt",
  plywood: "Sperrholz",
  curtain: "Vorhang",
  glass: "Glas",
  "chair leg (in the cone)": "Stuhlbein (im Kegel)",
  "no echo": "kein Echo",
  "no return": "kein Rücklauf",
  "ultrasonic reads": "Ultraschall misst",
  "laser reads": "Laser misst",
  "echo round trip": "Echo-Rundreise",
  "light round trip": "Licht-Rundreise",
  "Target distance": "Zielentfernung",
  "Side obstacle": "Seitliches Hindernis",
  "chair leg at 1.2 m": "Stuhlbein bei 1,2 m",
  "Target material": "Zielmaterial",
  "Ultrasonic verdict": "Ultraschall-Urteil",
  "blind — the curtain swallowed the chirp": "blind — der Vorhang hat den Zirp geschluckt",
  "fooled — nearest echo in the cone wins": "getäuscht — das nächste Echo im Kegel gewinnt",
  "Laser verdict": "Laser-Urteil",
  "blind — glass reflected the beam away": "blind — das Glas hat den Strahl weggespiegelt",
  "honest — thin beam, no cone": "ehrlich — dünner Strahl, kein Kegel",
  "true angle": "wahrer Winkel",
  accelerometer: "Beschleunigungssensor",
  "gyro (integrated)": "Gyro (integriert)",
  "fused estimate": "fusionierte Schätzung",
  "the board": "das Brett",
  "gyro drift after 60 s": "Gyro-Drift nach 60 s",
  "Board tilt": "Brettneigung",
  Vibration: "Vibration",
  "Gyro bias": "Gyro-Bias",
  Accelerometer: "Beschleunigungssensor",
  "noisy now, honest on average": "verrauscht im Moment, ehrlich im Mittel",
  Gyro: "Gyro",
  "smooth now, drifting": "ruhig im Moment, driftet",
  "the gyro trace re-zeroes every 45 s — real drift never does": "die Gyro-Spur nullt sich alle 45 s — echte Drift nie",
  "the blend": "die Mischung",
  "trust in the gyro": "Vertrauen in den Gyro",
  "gravity unplugged!": "Schwerkraft abgestöpselt!",
  "pull-home time": "Heimzieh-Zeit",
  "Pull-home time": "Heimzieh-Zeit",
  Alpha: "Alpha",
  "Fused estimate": "Fusionierte Schätzung",
  "pure gyro — drift is back": "reiner Gyro — die Drift ist zurück",
  "vibration leaking through": "Vibration sickert durch",
  "steady and drift-free": "ruhig und driftfrei",

  /* ---- unit 3: control ---- */
  "hysteresis band": "Hysterese-Band",
  coasting: "rollt aus",
  "switches / s": "Schaltvorgänge / s",
  "wobble ±": "Wackeln ±",
  "Hysteresis band": "Hysterese-Band",
  "Sensor noise": "Sensorrauschen",
  Switching: "Schalten",
  "chattering — noise is flipping the decision": "flattert — das Rauschen kippt die Entscheidung",
  calm: "ruhig",
  Oscillation: "Schwingung",
  "never zero": "nie null",
  "two settings can bracket a target, never hold it": "zwei Stellungen können ein Ziel einklammern, nie halten",
  gravity: "Schwerkraft",
  "the arm": "der Arm",
  Kp: "Kp",
  Ki: "Ki",
  Kd: "Kd",
  Overshoot: "Überschwingen",
  "oscillating!": "schwingt!",
  "Steady-state error": "Bleibende Regelabweichung",
  "Settling time": "Einschwingzeit",
  "> 8 s": "> 8 s",
  lap: "Runde",
  DNF: "DNF",
  departures: "Abflüge",
  "worst error": "größter Fehler",
  "Kp (steering)": "Kp (Lenkung)",
  "Kd (damping)": "Kd (Dämpfung)",
  "clean lap in": "saubere Runde in",
  "lap with": "Runde mit",
  "departure(s)": "Abflug/Abflügen",
  "lost the line for good": "die Linie endgültig verloren",
  "of the lane": "der Spurbreite",
  "raise speed → wobble → add Kd → repeat": "Tempo rauf → Wackeln → Kd dazu → wiederholen",

  /* ---- unit 4: arms & grippers ---- */
  "outer edge: arm straight": "Außenrand: Arm gestreckt",
  "inner edge: arm folded": "Innenrand: Arm gefaltet",
  shoulder: "Schulter",
  elbow: "Ellbogen",
  "hand x": "Hand x",
  "hand y": "Hand y",
  reach: "Reichweite",
  "Shoulder θ₁": "Schulter θ₁",
  "Elbow θ₂": "Ellbogen θ₂",
  "Forward kinematics": "Vorwärtskinematik",
  Workspace: "Arbeitsraum",
  "ring from": "Ring von",
  "unreachable — cos θ₂ left [−1, 1]": "unerreichbar — cos θ₂ hat [−1, 1] verlassen",
  "the other answer": "die andere Antwort",
  "target distance": "Zielentfernung",
  manipulability: "Beweglichkeit",
  "singularity: near-straight arm, joints must thrash": "Singularität: fast gestreckter Arm, die Gelenke müssen rasen",
  "Target x": "Ziel x",
  "Target y": "Ziel y",
  Elbow: "Ellbogen",
  "elbow-up": "Ellbogen oben",
  "elbow-down": "Ellbogen unten",
  "IK verdict": "IK-Urteil",
  "solved — two ways": "gelöst — auf zwei Arten",
  unreachable: "unerreichbar",
  "cos θ₂": "cos θ₂",
  Singularity: "Singularität",
  "close — route around this pose": "nah — um diese Pose herumplanen",
  "comfortably away": "bequem entfernt",
  "slipping…": "rutscht…",
  "the grasp window": "das Greif-Fenster",
  slips: "rutscht",
  holds: "hält",
  crushes: "zerdrückt",
  floor: "Boden",
  ceiling: "Decke",
  "your grip": "dein Griff",
  "window width": "Fensterbreite",
  "closed!": "geschlossen!",
  Object: "Objekt",
  "steel cube": "Stahlwürfel",
  apple: "Apfel",
  egg: "Ei",
  "paper cup": "Pappbecher",
  "Grip force": "Griffkraft",
  Fingertips: "Fingerspitzen",
  rigid: "starr",
  compliant: "nachgiebig",
  Surface: "Oberfläche",
  dry: "trocken",
  wet: "nass",
  Outcome: "Ergebnis",
  "holds — inside the window": "hält — im Fenster",
  "slips — below the friction floor": "rutscht — unter dem Reibungsboden",
  "crushed — above the ceiling": "zerdrückt — über der Decke",
  Window: "Fenster",
  "closed — no safe grip exists": "geschlossen — es gibt keinen sicheren Griff",

  /* ---- unit 5: wheels & navigation ---- */
  "the intended square": "das geplante Quadrat",
  "really here": "wirklich hier",
  "believes it's here": "glaubt, hier zu sein",
  "distance driven": "gefahrene Strecke",
  "final position lie": "finale Positionslüge",
  "final heading lie": "finale Richtungslüge",
  "Wheel slip": "Radschlupf",
  "Track miscalibration": "Spurweiten-Fehlkalibrierung",
  "After one lap": "Nach einer Runde",
  "of fiction": "Fiktion",
  "locally excellent, globally rotten": "lokal exzellent, global verrottet",
  "calibrate first — then anchor to a map": "erst kalibrieren — dann an einer Karte verankern",
  belief: "Glaube",
  coverage: "Abdeckung",
  steps: "Schritte",
  "dark: wall evidence · light: cleared free · grey: unknown": "dunkel: Wand-Evidenz · hell: freigeräumt · grau: unbekannt",
  Drive: "Fahren",
  "↺ wipe map": "↺ Karte wischen",
  "Odometry drift": "Odometrie-Drift",
  Coverage: "Abdeckung",
  "of the flat mapped": "der Wohnung kartiert",
  "Pose honesty": "Posen-Ehrlichkeit",
  "perfect — the map will be crisp": "perfekt — die Karte wird gestochen scharf",
  "drifting — watch walls smear and double": "driftet — sieh zu, wie Wände schmieren und sich doppeln",
  "a smeared map is a pose problem, not a lidar problem": "eine verschmierte Karte ist ein Posen-Problem, kein Lidar-Problem",
  "cells explored": "Zellen erkundet",
  "path length": "Pfadlänge",
  "no path!": "kein Pfad!",
  Map: "Karte",
  hall: "Halle",
  office: "Büro",
  maze: "Labyrinth",
  Algorithm: "Algorithmus",
  "Inflation radius": "Aufblähradius",
  "Search effort": "Suchaufwand",
  "cells expanded": "Zellen expandiert",
  Route: "Route",
  "cells long": "Zellen lang",
  "none — inflation closed the last door": "keine — das Aufblähen hat die letzte Tür geschlossen",
  "same map, both algorithms — compare the ripples": "gleiche Karte, beide Algorithmen — vergleiche die Wellen",

  /* ---- unit 6: robot school ---- */
  "spawn zone": "Spawn-Zone",
  "amber dots: demos · rings: fresh tests · dashes: where the policy actually reached": "gelbe Punkte: Demos · Ringe: frische Tests · Striche: wohin die Policy wirklich griff",
  demos: "Demos",
  "success rate": "Erfolgsquote",
  trials: "Versuche",
  "Teach target x": "Lehrziel x",
  "Teach target y": "Lehrziel y",
  Sloppiness: "Schlampigkeit",
  Studio: "Studio",
  "🎬 Record demo here": "🎬 Demo hier aufnehmen",
  "🧪 Test 10 fresh targets": "🧪 10 frische Ziele testen",
  "🗑 Forget everything": "🗑 Alles vergessen",
  "Success rate": "Erfolgsquote",
  "fresh targets": "frischen Zielen",
  untested: "ungetestet",
  Dataset: "Datensatz",
  "demos — coverage is the program": "Demos — die Abdeckung ist das Programm",
  "failures cluster where demos are missing": "Fehlschläge häufen sich, wo Demos fehlen",
  "SIMULATION (training worlds)": "SIMULATION (Trainingswelten)",
  "REALITY (deployed)": "REALITÄT (deployt)",
  REALITY: "REALITÄT",
  "not deployed yet": "noch nicht deployt",
  "gains changed since deploy — deploy again": "Verstärkungen seit dem Deploy geändert — nochmal deployen",
  Randomization: "Randomisierung",
  "Ship it": "Raus damit",
  "🚀 DEPLOY": "🚀 DEPLOY",
  "Sim score": "Sim-Punktzahl",
  "Deployed score": "Deploy-Punktzahl",
  "press DEPLOY": "drücke DEPLOY",
  "(stale)": "(veraltet)",
  "train across many wrong worlds → survive the real one": "trainiere in vielen falschen Welten → überlebe die echte",
};

let active: Record<string, string> | null = null;

export function setLabDictionary(dict: Record<string, string> | null) {
  active = dict;
}

/** Translate a lab string via the active dictionary; unknown strings pass through. */
export function tl(s: string): string {
  return active?.[s] ?? s;
}
